// <auto-generated />
using System;
using AppReleases.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppReleases.DataAccess.Migrations
{
    [DbContext(typeof(AppReleasesDbContext))]
    partial class AppReleasesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ApplicationEntity", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("DefaultLatestReleaseLifetime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DefaultReleaseLifetime")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MainBranch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ApplicationId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.AssetEntity", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BranchEntity", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("LatestReleaseLifetime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<TimeSpan?>("ReleaseLifetime")
                        .HasColumnType("interval");

                    b.Property<bool>("UseDefaultReleaseLifetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("BranchId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BuiltInstallerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuilderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuilderId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("BuiltInstallers");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BundleEntity", b =>
                {
                    b.Property<Guid>("BundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("BundleId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.InstallerBuilderUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuilderKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("InstallerLifetime")
                        .HasColumnType("interval");

                    b.Property<string>("Settings")
                        .HasMaxLength(1024)
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("InstallerBuilderUsages");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ReleaseAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ReleaseAssets");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ReleaseEntity", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReleaseNotes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ReleaseId");

                    b.HasIndex("BranchId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.TokenEntity", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TokenId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BranchEntity", b =>
                {
                    b.HasOne("AppReleases.DataAccess.Entities.ApplicationEntity", "Application")
                        .WithMany("Branches")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BuiltInstallerEntity", b =>
                {
                    b.HasOne("AppReleases.DataAccess.Entities.InstallerBuilderUsageEntity", "Builder")
                        .WithMany("BuiltInstallers")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppReleases.DataAccess.Entities.ReleaseEntity", "Release")
                        .WithMany("BuiltInstallers")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BundleEntity", b =>
                {
                    b.HasOne("AppReleases.DataAccess.Entities.ReleaseEntity", "Release")
                        .WithMany("Bundles")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.InstallerBuilderUsageEntity", b =>
                {
                    b.HasOne("AppReleases.DataAccess.Entities.ApplicationEntity", "Application")
                        .WithMany("InstallerBuilders")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ReleaseAssetEntity", b =>
                {
                    b.HasOne("AppReleases.DataAccess.Entities.AssetEntity", "Asset")
                        .WithMany("ReleaseAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppReleases.DataAccess.Entities.ReleaseEntity", "Release")
                        .WithMany("ReleaseAssets")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ReleaseEntity", b =>
                {
                    b.HasOne("AppReleases.DataAccess.Entities.BranchEntity", "Branch")
                        .WithMany("Releases")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("InstallerBuilders");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.AssetEntity", b =>
                {
                    b.Navigation("ReleaseAssets");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.BranchEntity", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.InstallerBuilderUsageEntity", b =>
                {
                    b.Navigation("BuiltInstallers");
                });

            modelBuilder.Entity("AppReleases.DataAccess.Entities.ReleaseEntity", b =>
                {
                    b.Navigation("BuiltInstallers");

                    b.Navigation("Bundles");

                    b.Navigation("ReleaseAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
